# Generated by Django 5.0.2 on 2024-03-05 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=30, verbose_name='Salutation')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('post_code', models.CharField(blank=True, max_length=10, verbose_name='Post code')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('show_in_phonelist', models.BooleanField(default=False, verbose_name='Show in phonelist')),
                ('internal_note', models.CharField(blank=True, max_length=250, verbose_name='Internal note')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
