# Generated by Django 5.0.4 on 2024-04-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faultasset',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='faultcomment',
            options={'ordering': ['id'], 'permissions': (('svjis_add_fault_comment', 'Can add Fault comment'),)},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(max_length=50, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Subject'),
        ),
    ]
