# Generated by Django 5.0.6 on 2024-07-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_faultasset_options_alter_faultcomment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Header')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'ordering': ['order'],
                'permissions': (('svjis_edit_useful_link', 'Can edit Useful Links'),),
            },
        ),
    ]
