# Generated by Django 5.0.2 on 2024-02-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articlemenu_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemenu',
            options={'ordering': ['description']},
        ),
        migrations.AddField(
            model_name='article',
            name='menu',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.articlemenu'),
            preserve_default=False,
        ),
    ]
