# Generated by Django 5.0.3 on 2024-03-14 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_board_building_buildingentrance_buildingunit_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible_for_all',
            field=models.BooleanField(default=False, verbose_name='Visible for all'),
        ),
        migrations.AddField(
            model_name='article',
            name='visible_for_group',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AddField(
            model_name='article',
            name='watching_users',
            field=models.ManyToManyField(related_name='watching_article_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
