# Generated by Django 5.0.3 on 2024-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_board_building_buildingentrance_buildingunit_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible_for_all',
            field=models.BooleanField(default=False, verbose_name='Visible for all'),
        ),
        migrations.AddField(
            model_name='article',
            name='visible_for_group',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
