# Generated by Django 5.1.5 on 2025-02-02 20:06

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articlecomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='header_picture',
            field=models.FileField(blank=True, null=True, upload_to=articles.models.company_directory_path, verbose_name='Header picture'),
        ),
    ]
