# Generated by Django 5.1.6 on 2025-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_company_header_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_language',
            field=models.CharField(blank=True, max_length=2, verbose_name='Website language'),
        ),
    ]
