# Generated by Django 5.2.1 on 2025-06-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_company_header_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleasset',
            options={'ordering': ['id']},
        ),
    ]
