# Generated by Django 5.0.2 on 2024-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_allow_comments_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
    ]
