# Generated by Django 5.2.4 on 2025-08-14 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articleasset_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('modified', 'Modified'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('created', 'Created')], default='modified', max_length=10, verbose_name='Type')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('fault_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='articles.faultreport')),
                ('resolver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_fault_report_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_fault_report_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
