# Generated by Django 5.2.7 on 2025-11-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_faultreportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=1000, verbose_name='UserAgent'),
        ),
    ]
