# Generated by Django 5.2.8 on 2025-11-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articlelog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='land_registry_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Land Registration No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Registration No.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_registration_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='VAT Registration No.'),
        ),
    ]
