# Generated by Django 5.0.3 on 2024-03-26 20:54

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_adverttype_advert_advertasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Body (markdown)'),
        ),
    ]
