# Generated by Django 5.0.3 on 2024-03-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_adverttype_advert_advertasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='article',
            name='perex',
            field=models.TextField(verbose_name='Perex'),
        ),
    ]
