# Generated by Django 5.2.9 on 2025-12-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_building_land_registry_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
