# Generated by Django 6.0.7 on 2026-07-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_slug_alter_faultreport_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultreport',
            name='slug',
        ),
    ]
