# Generated by Django 6.0.8 on 2026-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_faultreport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelog',
            name='referer',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Referer'),
        ),
    ]
