from . import views, views_contact, views_personal_settings, views_redaction, views_admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.main_view, name='main'),
    path('main/<int:menu>', views.main_filtered_view, name='main_filtered'),
    path('article/<int:pk>/', views.article_view, name='article'),
    path('article_comment_save/', views.article_comment_save_view, name='article_comment_save'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('contact_company/', views_contact.contact_view, name='contact_company'),
    path('contact_phonelist/', views_contact.phonelist_view, name='contact_phonelist'),
    path('personal_settings_edit/', views_personal_settings.personal_settings_edit_view, name='personal_settings_edit'),
    path('personal_settings_save/', views_personal_settings.personal_settings_save_view, name='personal_settings_save'),
    path('personal_settings_password/', views_personal_settings.personal_settings_password_view, name='personal_settings_password'),
    path('personal_settings_password_save/', views_personal_settings.personal_settings_password_save_view, name='personal_settings_password_save'),
    path('redaction_menu/', views_redaction.redaction_menu_view, name='redaction_menu'),
    path('redaction_menu_edit/<int:pk>/', views_redaction.redaction_menu_edit_view, name='redaction_menu_edit'),
    path('redaction_menu_save/', views_redaction.redaction_menu_save_view, name='redaction_menu_save'),
    path('redaction_menu_delete/<int:pk>/', views_redaction.redaction_menu_delete_view, name='redaction_menu_delete'),
    path('redaction_article/', views_redaction.redaction_article_view, name='redaction_article'),
    path('redaction_article_edit/<int:pk>/', views_redaction.redaction_article_edit_view, name='redaction_article_edit'),
    path('redaction_article_save/', views_redaction.redaction_article_save_view, name='redaction_article_save'),
    path('redaction_article_delete/<int:pk>/', views_redaction.redaction_article_delete_view, name='redaction_article_delete'),
    path('redaction_article_asset_save/', views_redaction.redaction_article_asset_save_view, name='redaction_article_asset_save'),
    path('redaction_article_asset_delete//<int:pk>/', views_redaction.redaction_article_asset_delete_view, name='redaction_article_asset_delete'),
    path('redaction_news/', views_redaction.redaction_news_view, name='redaction_news'),
    path('redaction_news_edit/<int:pk>/', views_redaction.redaction_news_edit_view, name='redaction_news_edit'),
    path('redaction_news_save/', views_redaction.redaction_news_save_view, name='redaction_news_save'),
    path('redaction_news_delete/<int:pk>/', views_redaction.redaction_news_delete_view, name='redaction_news_delete'),
    path('admin_company_edit/', views_admin.admin_company_edit_view, name='admin_company_edit'),
    path('admin_company_save/', views_admin.admin_company_save_view, name='admin_company_save'),
    path('admin_board/', views_admin.admin_board_view, name='admin_board'),
    path('admin_board_edit/<int:pk>/', views_admin.admin_board_edit_view, name='admin_board_edit'),
    path('admin_board_save/', views_admin.admin_board_save_view, name='admin_board_save'),
    path('admin_board_delete/<int:pk>/', views_admin.admin_board_delete_view, name='admin_board_delete'),
    path('admin_building_edit/', views_admin.admin_building_edit_view, name='admin_building_edit'),
    path('admin_building_save/', views_admin.admin_building_save_view, name='admin_building_save'),
    path('admin_entrance/', views_admin.admin_entrance_view, name='admin_entrance'),
    path('admin_entrance_edit/<int:pk>/', views_admin.admin_entrance_edit_view, name='admin_entrance_edit'),
    path('admin_entrance_save/', views_admin.admin_entrance_save_view, name='admin_entrance_save'),
    path('admin_entrance_delete/<int:pk>/', views_admin.admin_entrance_delete_view, name='admin_entrance_delete'),
    path('admin_building_unit/', views_admin.admin_building_unit_view, name='admin_building_unit'),
    path('admin_building_unit_edit/<int:pk>/', views_admin.admin_building_unit_edit_view, name='admin_building_unit_edit'),
    path('admin_building_unit_save/', views_admin.admin_building_unit_save_view, name='admin_building_unit_save'),
    path('admin_building_unit_delete/<int:pk>/', views_admin.admin_building_unit_delete_view, name='admin_building_unit_delete'),
    path('admin_building_unit_owners/<int:pk>/', views_admin.admin_building_unit_owners_view, name='admin_building_unit_owners'),
    path('admin_building_unit_owners_save', views_admin.admin_building_unit_owners_save_view, name='admin_building_unit_owners_save'),
    path('admin_building_unit_owners_delete/<int:pk>/<int:owner>/', views_admin.admin_building_unit_owners_delete_view, name='admin_building_unit_owners_delete'),
    path('admin_user/', views_admin.admin_user_view, name='admin_user'),
    path('admin_user_edit/<int:pk>/', views_admin.admin_user_edit_view, name='admin_user_edit'),
    path('admin_user_save/', views_admin.admin_user_save_view, name='admin_user_save'),
    path('admin_user_owns/<int:pk>/', views_admin.admin_user_owns_view, name='admin_user_owns'),
    path('admin_user_owns_save', views_admin.admin_user_owns_save_view, name='admin_user_owns_save'),
    path('admin_user_owns_delete/<int:pk>/<int:owner>/', views_admin.admin_user_owns_delete_view, name='admin_user_owns_delete'),
    path('admin_group/', views_admin.admin_group_view, name='admin_group'),
    path('admin_group_edit/<int:pk>/', views_admin.admin_group_edit_view, name='admin_group_edit'),
    path('admin_group_save/', views_admin.admin_group_save_view, name='admin_group_save'),
    path('admin_group_delete/<int:pk>/', views_admin.admin_group_delete_view, name='admin_group_delete'),
    path('admin_preferences/', views_admin.admin_preferences_view, name='admin_preferences'),
    path('admin_preferences_edit/<int:pk>/', views_admin.admin_preferences_edit_view, name='admin_preferences_edit'),
    path('admin_preferences_save/', views_admin.admin_preferences_save_view, name='admin_preferences_save'),
    path('admin_preferences_delete/<int:pk>/', views_admin.admin_preferences_delete_view, name='admin_preferences_delete'),
    path('admin_messages/', views_admin.admin_messages_view, name='admin_messages'),
    path('lost_password/', views_personal_settings.lost_password_view, name='lost_password'),
    path('lost_password_send/', views_personal_settings.lost_password_send_view, name='lost_password_send'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
