name: Makemessages

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  pull-requests: write

jobs:
  makemessages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: |
        uv sync
        sudo apt-get install gettext

    - name: Make messages
      run: |
        source .venv/bin/activate
        cd svjis
        python manage.py makemessages --all
        python manage.py compilemessages

    - name: Archive messages
      uses: actions/upload-artifact@v7
      with:
        name: Messages
        path: svjis/articles/locale/*
        overwrite: true
        retention-days: 60
